### ISSUE TITLE
Support for symfony3

### ISSUE THREAD

**Issue by pije76** [harentius/blog-bundle#1]
Any chance for symfony3?

**Comment by harentius** [comment]
Yes. I just successfully run my project, which uses this bundle under Symfony 3.3.
I'll collect all changes, commit them to the bundle and make release soon.

**Comment by harentius** [comment]
Released version 2.0 with Symfony >=3.0 support

**Comment by pije76** [comment]
Great! Thank you so much

**Comment by harentius** [comment]
You are welcome
