### ISSUE TITLE
Support Symfony 5

### ISSUE THREAD

**Issue by tacman** [harentius/blog-bundle#19]
I think it's worth supporting Symfony 5, even if you need to bump this to a new version.

Fortunately, going from 4.4 to 5 is simply a matter of removing deprecations.

I know you just pushed the tag for Symfony 4, thanks!

**Comment by harentius** [comment]
@tacman, yes, I updated to 4 keeping that in mind)
Problem is that I depend on some bundles which still not supports Symfony 5 (like SonataAdminBundle).
I subscribed to their updates and will add support of Symfony 5 once they release new version with Symfony 5 support.

**Comment by harentius** [comment]
It's been a while
Now the bundle supports Symfony 6 and 7.
